### ISSUE TITLE
网络状态不更新

### ISSUE THREAD

**Issue by simplebam** [tianma8023/NetDetector#1]
## 测试环境
* 系统版本：Android原生 7.1.2
* 型号：rk3288（一个杂牌）

## 问题描述
我发现机器开始时候可以检测到网络的变化，但中途如果网络变化比如wifi关闭或者开启，它都不会变化了

**Comment by tianma8023** [comment]
@simplebam 
Hi，在这个库的 [原理分析及代码介绍](https://github.com/tianma8023/NetDetector/blob/master/introduction.md) 中，可以看到是动态注册的网络变化，也就是说需要在App正在运行的时候调用正常。基于你说的问题，是不是可能因为App失活或者其他方面，从而没收到广播呢？

还有，因为这是一个简单库（甚至是示例级别的，可能还没有能够到实际的生产应用上去），仅提供一种思路吧~
